Pandas problem

Creating a Series

In [999]:
import pandas as pd
a=(1,2,3,4,5)#tuple
print("using tuple:\n",pd.Series(a))
b=[9,6,3,2]#list
print("using list\n",pd.Series(b))
c={1:"sanya",2:"Anmol"}
print("Using dict  :\n",pd.Series(c))

using tuple:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
using list
 0    9
1    6
2    3
3    2
dtype: int64
Using dict  :
 1    sanya
2    Anmol
dtype: object

Series to List Conversion

In [1000]:
a=[1,2,3,4]
s=pd.Series(a)
b=list(a)
print(b)
print(type(b))

[1, 2, 3, 4]
<class 'list'>

Series Arithmetic

In [1001]:
a=pd.Series([2, 4, 6, 8, 10])
b=pd.Series([1, 3, 5, 7, 9])
print("Add :\n",a+b)
print("Subtract :\n",a-b)
print("Multiple :\n",a*b)
print("Divide :\n",a/b)

Add :
 0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract :
 0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiple :
 0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide :
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

Series Comparison

In [1002]:
a=pd.Series([2, 4, 6, 8, 10])
b=pd.Series([1, 3, 5, 7, 10])
print("Equal:",a==b)
print("greter then :\n",a>b)
print("less then :\n",a<b)
print("greter then equal :\n",a>=b)
print("less then equal :\n",a<=b)

Equal: 0    False
1    False
2    False
3    False
4     True
dtype: bool
greter then :
 0     True
1     True
2     True
3     True
4    False
dtype: bool
less then :
 0    False
1    False
2    False
3    False
4    False
dtype: bool
greter then equal :
 0    True
1    True
2    True
3    True
4    True
dtype: bool
less then equal :
 0    False
1    False
2    False
3    False
4     True
dtype: bool

Dict to Series

In [1003]:
dict={'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
se=pd.Series(dict)
se

a    100
b    200
c    300
d    400
e    800
dtype: int64

 Array to Series

In [1004]:
arr=[10,20,30, 40,50]
print(pd.Series(arr))

0    10
1    20
2    30
3    40
4    50
dtype: int64

Change Series DataType

In [1005]:
s=pd.Series([100,200,"Python",300.12,400])
print("Original Series :")
print(s)
print("Change the said data type to numeric")
c=pd.to_numeric(s,errors='coerce')
print(c)

Original Series :
0       100
1       200
2    Python
3    300.12
4       400
dtype: object
Change the said data type to numeric
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

DF Column to Series

In [1006]:
data=pd.DataFrame({'col1':[1,2,3,4,7,11],'col2':[4,5,6,9,5,0],'col3':[7,5,8,12,1,11]})
print("Datafarme :\n",data)
print("1st column as series :\n")
print(pd.Series(data['col1']))

Datafarme :
    col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11
1st column as series :

0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64

Series to Array

In [1007]:
a=pd.Series([1,2,3,4])
print("Original series : \n")
print(a)
print("Series to Array \n")
arr=a.values
print(arr)

Original series :

0    1
1    2
2    3
3    4
dtype: int64
Series to Array

[1 2 3 4]

Flatten Series of Lists

In [1008]:
A=pd.Series({0:['Red','Green','White'],1:['Red','Green'],2:['Yellow']})
print("Original Series :\n",A)
print("One Series ")
b=A.values
print(b)

Original Series :
 0    [Red, Green, White]
1           [Red, Green]
2               [Yellow]
dtype: object
One Series
[list(['Red', 'Green', 'White']) list(['Red', 'Green']) list(['Yellow'])]

# Pandas DataFrame

In [1009]:
#Creating Data Frame with dict
import pandas as pd
dict={'Name':['Sanya','Anmol','Drishya','Neetu','Umesh','Manya'],
      'Age':[20,22,23,42,52,16],
      'Sex':['Female','Male','Female','Female','Male','Female']}
data_frame=pd.DataFrame(dict)
data_frame

      Name  Age     Sex
0    Sanya   20  Female
1    Anmol   22    Male
2  Drishya   23  Female
3    Neetu   42  Female
4    Umesh   52    Male
5    Manya   16  Female

In [1010]:
# DataFrame with index lavel
import pandas as pd
dict={'Name':['Sanya','Anmol','Drishya','Neetu','Umesh','Manya'],
      'Age':[20,22,23,42,52,16],
      'Sex':['Female','Male','Female','Female','Male','Female']}
l=pd.Series(['a','b','c','d','e','f'])
data_frame=pd.DataFrame(dict,index=l)
data_frame

      Name  Age     Sex
a    Sanya   20  Female
b    Anmol   22    Male
c  Drishya   23  Female
d    Neetu   42  Female
e    Umesh   52    Male
f    Manya   16  Female

In [1011]:
# Summary of dataframe
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, a to f
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   Sex     6 non-null      object
dtypes: int64(1), object(2)
memory usage: 192.0+ bytes

In [1012]:
 #Selecting the First 2 Rows
data_frame.iloc[:3]

      Name  Age     Sex
a    Sanya   20  Female
b    Anmol   22    Male
c  Drishya   23  Female

In [1013]:
#Selecting 'name' and sex Columns
#data_frame.Name
data_frame[["Name","Sex"]]

      Name     Sex
a    Sanya  Female
b    Anmol    Male
c  Drishya  Female
d    Neetu  Female
e    Umesh    Male
f    Manya  Female

In [1014]:
#Selecting Specific Columns and Rows
data_frame.iloc[[1,2,3],[1,2]]

   Age     Sex
b   22    Male
c   23  Female
d   42  Female

In [1015]:
#Selecting Rows Where Age > 18
data_frame[data_frame['Age']>18]

      Name  Age     Sex
a    Sanya   20  Female
b    Anmol   22    Male
c  Drishya   23  Female
d    Neetu   42  Female
e    Umesh   52    Male

In [1016]:
#Counting Rows and Columns
c=data_frame.columns
i=data_frame.index
print("Number of columns :",len(c))
print("Number of  Rows :",len(i))

Number of columns : 3
Number of  Rows : 6

In [1017]:
mapping = {
    'Sanya':'study',
    'Anmol': 'job',
    'Umesh':'farmer'
}

data_frame['work'] = data_frame['Name'].map(mapping)
data_frame

      Name  Age     Sex    work
a    Sanya   20  Female   study
b    Anmol   22    Male     job
c  Drishya   23  Female     NaN
d    Neetu   42  Female     NaN
e    Umesh   52    Male  farmer
f    Manya   16  Female     NaN

In [1018]:
#Selecting Rows with Missing Score
data_frame[data_frame['work'].isna()]

      Name  Age     Sex work
c  Drishya   23  Female  NaN
d    Neetu   42  Female  NaN
f    Manya   16  Female  NaN

In [1019]:
#Selecting Rows Where Score is Between 20 and 35
data_frame[data_frame['Age'].between(20,35) ]

      Name  Age     Sex   work
a    Sanya   20  Female  study
b    Anmol   22    Male    job
c  Drishya   23  Female    NaN

In [1020]:
# Selecting Rows with age < 25 and sex=female
data_frame[(data_frame['Age']<25) & (data_frame['Sex']=='Female')]

      Name  Age     Sex   work
a    Sanya   20  Female  study
c  Drishya   23  Female    NaN
f    Manya   16  Female    NaN

In [1021]:
# Changing the age in a Specific Row
data_frame.loc['d','Age']=45
data_frame

      Name  Age     Sex    work
a    Sanya   20  Female   study
b    Anmol   22    Male     job
c  Drishya   23  Female     NaN
d    Neetu   45  Female     NaN
e    Umesh   52    Male  farmer
f    Manya   16  Female     NaN

In [1022]:
import pandas as pd
import numpy as np

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

labels = ['a','b','c','d','e','f','g','h','i','j']

df = pd.DataFrame(exam_data, index=labels)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [1023]:
#. Summing Examination Attempts
df['attempts'].sum()

np.int64(19)

In [1024]:
#Calculating the Mean of Scores
df['score'].mean()

np.float64(13.5625)

In [1025]:
# Appending and Deleting a New Row
mapping={'Name':"Suresh", 'score': 15.5, 'attempts': 1, 'qualify': "yes", 'label': "k"}
df.loc['k']=[1, 'Suresh', 'yes', 15.5]
df

        name   score attempts qualify
a  Anastasia    12.5        1     yes
b       Dima     9.0        3      no
c  Katherine    16.5        2     yes
d      James     NaN        3      no
e      Emily     9.0        2      no
f    Michael    20.0        3     yes
g    Matthew    14.5        1     yes
h      Laura     NaN        1      no
i      Kevin     8.0        2      no
j      Jonas    19.0        1     yes
k          1  Suresh      yes    15.5

In [1026]:
df=df.drop('k')
df

        name score attempts qualify
a  Anastasia  12.5        1     yes
b       Dima   9.0        3      no
c  Katherine  16.5        2     yes
d      James   NaN        3      no
e      Emily   9.0        2      no
f    Michael  20.0        3     yes
g    Matthew  14.5        1     yes
h      Laura   NaN        1      no
i      Kevin   8.0        2      no
j      Jonas  19.0        1     yes

In [1027]:
df.sort_values(by=['name','score'],ascending=[False,True])

        name score attempts qualify
f    Michael  20.0        3     yes
g    Matthew  14.5        1     yes
h      Laura   NaN        1      no
i      Kevin   8.0        2      no
c  Katherine  16.5        2     yes
j      Jonas  19.0        1     yes
d      James   NaN        3      no
e      Emily   9.0        2      no
b       Dima   9.0        3      no
a  Anastasia  12.5        1     yes

In [1028]:
#Replacing Column Values (qualify)
df['qualify']=df['qualify'].map({'yes':True,'no':False})
df

        name score attempts  qualify
a  Anastasia  12.5        1     True
b       Dima   9.0        3    False
c  Katherine  16.5        2     True
d      James   NaN        3    False
e      Emily   9.0        2    False
f    Michael  20.0        3     True
g    Matthew  14.5        1     True
h      Laura   NaN        1    False
i      Kevin   8.0        2    False
j      Jonas  19.0        1     True

In [1029]:
#Changing a Specific Name Value
#data_frame.loc['d','Age']=45
df.loc[df['name'] == 'James', 'name'] = 'suresh'
df

        name score attempts  qualify
a  Anastasia  12.5        1     True
b       Dima   9.0        3    False
c  Katherine  16.5        2     True
d     suresh   NaN        3    False
e      Emily   9.0        2    False
f    Michael  20.0        3     True
g    Matthew  14.5        1     True
h      Laura   NaN        1    False
i      Kevin   8.0        2    False
j      Jonas  19.0        1     True

In [1030]:
# Deleting a Column from the DataFrame
df.drop('attempts',axis=1)

        name score  qualify
a  Anastasia  12.5     True
b       Dima   9.0    False
c  Katherine  16.5     True
d     suresh   NaN    False
e      Emily   9.0    False
f    Michael  20.0     True
g    Matthew  14.5     True
h      Laura   NaN    False
i      Kevin   8.0    False
j      Jonas  19.0     True

In [1031]:
#Inserting a New Column
df.insert(3,'color',['red','blue,','green','red','blue','black','pink','grey','sunny','red'])
df

        name score attempts  color  qualify
a  Anastasia  12.5        1    red     True
b       Dima   9.0        3  blue,    False
c  Katherine  16.5        2  green     True
d     suresh   NaN        3    red    False
e      Emily   9.0        2   blue    False
f    Michael  20.0        3  black     True
g    Matthew  14.5        1   pink     True
h      Laura   NaN        1   grey    False
i      Kevin   8.0        2  sunny    False
j      Jonas  19.0        1    red     True

In [1032]:
import pandas as pd

exam_data = [
    {'name':'Anastasia', 'score':12.5},
    {'name':'Dima','score':9},
    {'name':'Katherine','score':16.5}
]

df = pd.DataFrame(exam_data)
print(df)

        name  score
0  Anastasia   12.5
1       Dima    9.0
2  Katherine   16.5

In [1033]:
#Iterating Over DataFrame Rows
for i in df.values:
    print(i)

['Anastasia' 12.5]
['Dima' 9.0]
['Katherine' 16.5]

In [1034]:
#Getting List from Column Headers
df.columns

Index(['name', 'score'], dtype='object')

In [1035]:
#Renaming DataFrame Columns
df.rename(columns={'name':'col1','score':'col2'})

        col1  col2
0  Anastasia  12.5
1       Dima   9.0
2  Katherine  16.5